// Copyright 2026 Joseph Cassman
// SPDX-License-Identifier: Apache-2.0

//!
//! https://projecteuler.net/problem=45
//!
//! Triangular, Pentagonal, and Hexagonal
//!
//! Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//!
//!    Triangle    T(n) = n·(n + 1) / 2     1, 3, 6, 10, 15, ...
//!    Pentagonal  P(n) = n·(3·n - 1) / 2   1, 5, 12, 22, 35, ...
//!    Hexagonal   H(n) = n·(2·n - 1)       1, 6, 15, 28, 45, ...
//!
//! It can be verified that T(285) = P(165) = H(143) = 40755.
//!
//! Find the next triangle number that is also pentagonal and hexagonal.
//!

use crate::etc::sequences::triangle::triangle;
use crate::etc::sequences::pentagonal::Pentagonal;
use crate::etc::sequences::hexagonal::Hexagonal;

pub fn run () {
    println!("\niterative method: {}\n", iterative());
}

fn iterative () -> u64 {
    const LIMIT: usize = 32768;
    let p: Vec<_> = Pentagonal::default().take(LIMIT).collect();
    let h: Vec<_> = Hexagonal::default().take(LIMIT).collect();

    for n in 286.. {
        let a = triangle(n);
        if p.binary_search(&a).is_ok() && h.binary_search(&a).is_ok() {
            return a;
        }
    }

    0
}
