// Copyright 2026 Joseph Cassman
// SPDX-License-Identifier: Apache-2.0

//!
//! https://projecteuler.net/problem=44
//!
//! Pentagon Numbers
//!
//! Pentagonal numbers are generated by the formula, P(n) = n·(3·n - 1) / 2.
//! The first ten pentagonal numbers are:
//!
//!    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
//!
//! It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8).
//! However, their difference, 70 - 22 = 48, is not pentagonal.
//!
//! Find the pair of pentagonal numbers, P(j) and P(k), for which their
//! sum and difference are pentagonal and D = |P(k) - P(j)| is minimised;
//! what is the value of D?
//!

use crate::etc::sequences::pentagonal::Pentagonal;

pub fn run () {
    println!("\niterative method: {}\n", iterative());
}

///
/// 𝑃(1) = 1
/// 𝑃(2) = 5
/// 𝑃(𝑛) = 𝑃(𝑛 − 1) + 3·𝑛 − 2 for 𝑛 ≥ 2
///      = 2·𝑃(𝑛 − 1) - 𝑃(𝑛 − 2) + 3 for 𝑛 ≥ 3
///
fn iterative () -> u64 {
    const LIMIT: usize = 4096;
    let p: Vec<_> = Pentagonal::default().take(LIMIT).collect();

    for j in 5..LIMIT {
    for k in (j + 1)..LIMIT {
        let sum = p[k] + p[j];
        let diff = p[k] - p[j];

        if p.binary_search(&sum).is_ok() && p.binary_search(&diff).is_ok() {
            return diff;
        }
    }}

    0
}
